Clean up and add support for non-RGB bulbs
L-I-Am/core pull request #1
Opened 2021-07-28 11:48 UTC by felipediel

I am cleaning up the code and adding support for non-RGB bulbs.

I don't have the devices to test. Perhaps I missed something. Mind having a look and doing some tests before accepting the changes?

2021-07-29 18:59 UTC, L-I-Am requested changes
First of all: Thanks for the Merge request!

I ran it locally and got some errors at first, changing `self._is_on` to `self._attr_is_on` solved these errors. 

Setting brightness seems to be working, but setting a custom RGB color does nothing. Debugged it some more and found some problems in the color modes, addressed in code.

2021-07-29 18:59 UTC, L-I-Am commented on homeassistant/components/broadlink/light.py
> +        elif ATTR_COLOR_MODE in kwargs:
color mode is never included in kwargs, that's why I implemented it originally to check if there's a temperature in the current kwargs or hs color in the current kwargs and to switch color mode depending on that (see lines 156 to 161 of original file).

I ran this locally and when setting a certain color, the only kwargs are: {'hs_color': (345.0, 100.0)}

2021-07-29 18:59 UTC, L-I-Am commented on homeassistant/components/broadlink/light.py
> +            self._is_on = data["pwr"]
```suggestion
            self._attr_is_on = data["pwr"]
```

2021-07-30 09:16 UTC, felipediel commented
Awesome, thank you! I am working on the changes.

2021-07-30 12:19 UTC, pr0fetul commented
Hi,
As I am testing to see if the new code works, the setup is the following:
 - I am not home, I am testing it remotely. 
 - I have 5 LB1 s configured in the Broadlink App and added already to HA, but only 1 is active at this moment, depending on the rule of the first one that connects. It can be the 1st, 2nd, 5th and so on. I have never had all 5 at the same time working. 
 - I cannot remove and re-add them at this moment - next week when I am back home I can do this, but for now, I am relying on the entities that are already added. 

I have cloned all the files from the broadlink integration in my setup (broadlink folder in custom_components folder), cleared py_cache folder and restarted HA. 
Once back - these were the initial errors (logger is set on debug on the broadlink component):
```
2021-07-30 15:02:08 ERROR (SyncWorker_4) [homeassistant.loader] The custom integration 'broadlink' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```
```
2021-07-30 15:02:27 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Smart Bulb Set 2 for broadlink
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/broadlink/__init__.py", line 35, in async_setup_entry
return await device.async_setup()
File "/usr/src/homeassistant/homeassistant/components/broadlink/device.py", line 110, in async_setup
update_manager = get_update_manager(self)
File "/usr/src/homeassistant/homeassistant/components/broadlink/updater.py", line 33, in get_update_manager
return update_managers[device.api.type](device)
KeyError: 'LB1'
```
I have added `"version": "1.0.0",` in the manifest.json file and restarted HA. Now the debug logs list these errors:
```
2021-07-30 15:16:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Smart Bulb Set 1' for broadlink integration not ready yet: [Errno -4000] Network timeout; Retrying in background
2021-07-30 15:16:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Smart Bulb Set 3' for broadlink integration not ready yet: [Errno -4000] Network timeout; Retrying in background
2021-07-30 15:16:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Smart Bulb 1' for broadlink integration not ready yet: [Errno -4000] Network timeout; Retrying in background
2021-07-30 15:16:04 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform opensky is taking over 10 seconds.
2021-07-30 15:16:07 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Smart Bulb Kitchen Balcony' for broadlink integration not ready yet: [Errno -4000] Network timeout; Retrying in background
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform broadlink
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform broadlink
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.remote] Error adding entities for domain remote with platform broadlink
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform broadlink
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.switch] Error while setting up broadlink platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.switch] Error while setting up broadlink platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (MainThread) [homeassistant.components.remote] Error while setting up broadlink platform for remote
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/broadlink/entity.py", line 55, in device_info
"connections": {(dr.CONNECTION_NETWORK_MAC, self._device.mac_address)},
AttributeError: 'BroadlinkDevice' object has no attribute 'mac_address'
2021-07-30 15:16:07 ERROR (Ma [...]

2021-07-30 12:30 UTC, felipediel commented
You cannot copy and paste the files at the custom components folder. This code is based on the latest dev branch, you need to set up a [dev environment](https://developers.home-assistant.io/docs/development_environment/).

2021-07-31 11:11 UTC, L-I-Am approved these changes
Tested locally and working for RGB-LB1 bulbs. Looks ok to me! thank you for putting in the time!

2021-07-31 11:44 UTC, felipediel commented
Awesome, thank you! I think we can proceed without testing non-RGB, but it would be good to have.

2021-08-02 08:37 UTC, merged